- src/OpenCvSharp.CPlusPlus/modules/core/Struct/Rect.cs
- src/OpenCvSharp.CPlusPlus/modules/core/Struct/Rectf.cs
- src/OpenCvSharp.Sandbox/Program.cs
- src/OpenCvSharp/Src/Struct/CvRect.cs
> Rect.Contains bugfix

- src/OpenCvSharp.CPlusPlus/modules/core/Mat/Mat_CvMethods.cs
Please add Mat.DistanceTransform().
> Add Mat.DistanceTransform()

- src/OpenCvSharpExtern/CMakeLists.txt
- src/OpenCvSharpExtern/core_Mat.h
- src/OpenCvSharpExtern/my_functions.h
- src/OpenCvSharpExtern/stitching.h
I created a patch to 3.0 branch for supporting UNIX.
Also I changed the encoding of src/OpenCvSharpExtern/core_Mat.h from Shift_JIS to UTF-8.
Please merge!
> Support GCC

- src/OpenCvSharp.Extensions/BitmapSourceConverter.cs
- src/OpenCvSharp.Extensions/WriteableBitmapConverter.cs
The ToMat conversions now work directly with the base class:
BitmapSource. This allows BitmapSource and WriteableBitmap to be
converted to the OpenCV Mat.
The ToBitmapSource methods now use the Conversions from within
WriteableBitmap.
Also changed visibility of WriteableBitmapConverter to allow usage of
the extension methods defined there.
Remarks:
- Did not refactor the Pixelformat mapping.
- Did not alter the actual conversion code.
- The removal of the ToMat methods from WriteableBitmapConverter would
be a breaking change if there wasn't that visibility bug that prevented
the use of any extension methods defined in that class.
> Refactored BitmapSourceConverter/WriteableBitmapConverter. Changed visibility.

- src/OpenCvSharp/modules/xfeatures2d/SURF.cs
- test/OpenCvSharp.Tests/features2d/SURFTest.cs
Change argment name to set value to DisposableCvObject.ptr and add test
> #331: SURF detector fails

- src/OpenCvSharp/Cv2/Cv2_highgui.cs
- src/OpenCvSharp/Modules/highgui/CvTrackbar.cs
- src/OpenCvSharp/PInvoke/NativeMethods_highgui.cs
- src/OpenCvSharpExtern/highgui.h
- test/OpenCvSharp.Tests/TestBase.cs
- test/OpenCvSharp.Tests/hiighgui/HighGuiTest.cs
- WaitKeyEx
- SetTrackbarMax
- SetTrackbarMin
- GetMouseWheelDelta
> highgui update

- src/OpenCvSharp/Modules/core/SparseMat.cs
> fix several SparseMat methods that called wrong NativeMethod..., sometimes causing an exception.

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
> fix RQDecomp3x3 bug

- src/OpenCvSharp/Modules/img_hash/ColorMomentHash.cs
- src/OpenCvSharp/PInvoke/NativeMethods_img_hash.cs
creating a ColorMomentHash would actually create an AverageHash algorithm object.
> fix ColorMomentHash

- src/OpenCvSharp/Modules/features2d/Feature2D.cs
- src/OpenCvSharpExtern/features2d_FeatureDetector.h
- test/OpenCvSharp.Tests/xfeatures2d/SIFTTest.cs
- test/OpenCvSharp.Tests/xfeatures2d/SURFTest.cs
> Feature2D fix base property/method access.

- src/OpenCvSharp/Modules/core/Mat/MatOfT.cs
- src/OpenCvSharp/Modules/xfeatures2d/LATCH.cs
- src/OpenCvSharp/Modules/xfeatures2d/LUCID.cs
- src/OpenCvSharp/PInvoke/NativeMethods_xfeatures2d.cs
- src/OpenCvSharpExtern/xfeatures2d.h
- test/OpenCvSharp.Tests/xfeatures2d/LATCHTest.cs
- test/OpenCvSharp.Tests/xfeatures2d/LUCIDTest.cs
- test/OpenCvSharp.Tests/xfeatures2d/SIFTTest.cs
> xfeatures2d: add LATCH and LUCID

- src/OpenCvSharp/Modules/core/FileNode.cs
- src/OpenCvSharp/Modules/core/FileNodeIterator.cs
- src/OpenCvSharp/Modules/core/FileStorage.cs
- src/OpenCvSharp/PInvoke/core/NativeMethods_core_FileNode.cs
- src/OpenCvSharp/PInvoke/core/NativeMethods_core_FileNodeIterator.cs
- src/OpenCvSharp/PInvoke/core/NativeMethods_core_FileStorage.cs
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj.filters
- src/OpenCvSharpExtern/core.cpp
- src/OpenCvSharpExtern/core_FileNode.h
- src/OpenCvSharpExtern/core_FileStorage.h
- src/OpenCvSharpExtern/my_types.h
- src/OpenCvSharpExtern/tracking.h
- src/OpenCvSharpExtern/tracking_MultiTracker.h
- test/OpenCvSharp.Tests/core/FileStorageTest.cs
> FileStorage capability

- src/OpenCvSharp/Cv2/Cv2_core.cs
- test/OpenCvSharp.Tests/core/CoreTest.cs
> add managed Partition

- src/OpenCvSharpExtern/objdetect_HOGDescriptor.h
- test/OpenCvSharp.Tests/objdetect/HOGDescriptorTest.cs
> HOGDescriptor.CellSize bug

- src/OpenCvSharpExtern/core_MatExpr.h
- test/OpenCvSharp.Tests/core/CoreTest.cs
> MatExpr subtraction bugfix

- src/OpenCvSharp/Cv2/Cv2_highgui.cs
- src/OpenCvSharp/Modules/highgui/CvMouseCallback.cs
- src/OpenCvSharp/Modules/highgui/Window.cs
> bugfix SetMouseCallback

- src/OpenCvSharp/Modules/aruco/DetectorParameters.cs
- src/OpenCvSharp/Modules/aruco/Enum/CornerRefineMethod.cs
- src/OpenCvSharp/PInvoke/NativeMethods_aruco.cs
- src/OpenCvSharpExtern/aruco.h
- test/OpenCvSharp.Tests/aruco/ArucoTest.cs
> add aruco DetectorParameters.CornerRefinementMethod

- OpenCvSharp.sln.DotSettings
- src/OpenCvSharp.Extensions/WriteableBitmapConverter.cs
- test/OpenCvSharp.Tests/WriteableBitmapConverterTest.cs
> AddDirtyRect

- nuget/OpenCvSharp4.Windows.nuspec
- nuget/OpenCvSharp4.nuspec
> System.Drawing.Common 4.5.0 -> 4.5.1

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- src/OpenCvSharp/Modules/calib3d/Enum/EssentialMatMethod.cs
- src/OpenCvSharp/PInvoke/calib3d/NativeMethods_calib3d.cs
- src/OpenCvSharpExtern/calib3d.h
> Issue 604: Added wrapper functions for calib3d: recoverPose and findEssentialMat

- OpenCvSharp.sln.DotSettings
- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- src/OpenCvSharp/Modules/calib3d/Enum/ChessboardFlags.cs
- src/OpenCvSharp/Modules/tracking/MultiTracker.cs
- src/OpenCvSharp/PInvoke/calib3d/NativeMethods_calib3d.cs
- src/OpenCvSharpExtern/calib3d.h
- test/OpenCvSharp.Tests/calib3d/Calib3dTest.cs
- test/OpenCvSharp.Tests/tracking/MultiTrackerTest.cs
> Add FindChessboardCornersSB, CheckChessboard and DrawFrameAxes

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- test/OpenCvSharp.Tests/calib3d/Calib3dTest.cs
> SolvePnP out -> ref

- src/OpenCvSharp/Modules/dnn/Net.cs
> Add Net.Backend and Net.Target enums

- src/OpenCvSharp/PInvoke/NativeMethods.cs
- test/OpenCvSharp.Tests/AppDmainTest.cs
I wish that the PR fixes #221 / fixes #236 / fixes #389 🙏 🙏 🙏
> Try removing NativeMethods.ErrorHandlerDefault to fix AppDomain error

- LICENSE
- nuget/OpenCvSharp4.Windows.nuspec
- nuget/OpenCvSharp4.nuspec
- nuget/OpenCvSharp4.runtime.ubuntu.18.04-x64.nuspec
- nuget/OpenCvSharp4.runtime.win.nuspec
> nuspec: change deprecated licenseUrl to license

- src/OpenCvSharp/Modules/core/Struct/Size2f.cs
- test/OpenCvSharp.Tests/core/SizeTest.cs
> fix Size2f constructor bug

- src/OpenCvSharp/Modules/core/FileStorage.cs
- src/OpenCvSharp/PInvoke/StdString.cs
- src/OpenCvSharp/PInvoke/core/NativeMethods_core_FileStorage.cs
- src/OpenCvSharpExtern/core_FileStorage.h
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
- test/OpenCvSharp.Tests/core/FileStorageTest.cs
> FileStorage: support long yaml string

- .gitmodules
- .travis.yml
- appveyor.yml
- nuget/OpenCvSharp4.Windows.nuspec
- nuget/OpenCvSharp4.nuspec
- nuget/OpenCvSharp4.runtime.ubuntu.18.04-x64.nuspec
- nuget/OpenCvSharp4.runtime.win.nuspec
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
- test/OpenCvSharp.Tests/text/TextDetectorTest.cs
- tool/OpenCvSharp.ReleaseMaker/MainForm.Designer.cs
TODO: TextDetectorCNN.detect does not work
> OpenCV 4.1.1

- Dockerfile
- src/OpenCvSharp/Modules/tracking/TrackerCSRT.cs
- src/OpenCvSharp/Modules/tracking/TrackerGOTURN.cs
- src/OpenCvSharp/PInvoke/traking/NativeMethods_tracking.cs
- src/OpenCvSharpExtern/tracking.h
- test/OpenCvSharp.Tests/tracking/TrackerCSRTTest.cs
> add TrackerCSRT

- src/OpenCvSharp/Modules/core/Struct/Scalar.cs
- test/OpenCvSharp.Tests/core/MatTest.cs
> Add test for #684

- src/OpenCvSharp/Modules/core/Mat/Mat.cs
> static dictionary

- OpenCvSharp.sln.DotSettings
- src/OpenCvSharp/Modules/core/Struct/DMatch.cs
- src/OpenCvSharp/Modules/core/Struct/KeyPoint.cs
- src/OpenCvSharp/Modules/core/Struct/MatType.cs
- src/OpenCvSharp/Modules/core/Struct/Point.cs
- src/OpenCvSharp/Modules/core/Struct/Point2d.cs
- src/OpenCvSharp/Modules/core/Struct/Point2f.cs
- src/OpenCvSharp/Modules/core/Struct/Point3d.cs
- src/OpenCvSharp/Modules/core/Struct/Point3f.cs
- src/OpenCvSharp/Modules/core/Struct/Point3i.cs
- src/OpenCvSharp/Modules/core/Struct/Range.cs
- src/OpenCvSharp/Modules/core/Struct/Rangef.cs
- src/OpenCvSharp/Modules/core/Struct/Rect.cs
- src/OpenCvSharp/Modules/core/Struct/Rect2d.cs
- src/OpenCvSharp/Modules/core/Struct/Rect2f.cs
- src/OpenCvSharp/Modules/core/Struct/RotatedRect.cs
- src/OpenCvSharp/Modules/core/Struct/Scalar.cs
- src/OpenCvSharp/Modules/core/Struct/Size.cs
- src/OpenCvSharp/Modules/core/Struct/Size2d.cs
- src/OpenCvSharp/Modules/core/Struct/Size2f.cs
- src/OpenCvSharp/Modules/core/Struct/TermCriteria.cs
> add readonly keyword to struct

- src/OpenCvSharp/Modules/core/Mat/MatOfT.cs
- src/OpenCvSharp/Modules/imgproc/ConnectedComponent.cs
- src/OpenCvSharpExtern/imgproc.h
- test/OpenCvSharp.Tests/imgproc/ConnectedComponentsTest.cs
> fix ConnectedComponentsEx

- src/OpenCvSharp/Cv2/Cv2_core.cs
- src/OpenCvSharp/Modules/core/Mat/Mat_CvMethods.cs
- src/OpenCvSharp/Modules/core/RNG.cs
- src/OpenCvSharp/Modules/core/RNG_MT19937.cs
- src/OpenCvSharp/Modules/xfeatures2d/StarDetector.cs
- src/OpenCvSharp/PInvoke/NativeMethods/core/NativeMethods_core.cs
- src/OpenCvSharp/Util/ArrayAddress.cs
- src/OpenCvSharp/Vector/VectorOfDMatch.cs
- src/OpenCvSharp/Vector/VectorOfDTreesNode.cs
- src/OpenCvSharp/Vector/VectorOfDTreesSplit.cs
- src/OpenCvSharp/Vector/VectorOfKeyPoint.cs
- src/OpenCvSharp/Vector/VectorOfPoint.cs
- src/OpenCvSharp/Vector/VectorOfPoint2d.cs
- src/OpenCvSharp/Vector/VectorOfPoint2f.cs
- src/OpenCvSharp/Vector/VectorOfPoint3f.cs
- src/OpenCvSharp/Vector/VectorOfRect.cs
- src/OpenCvSharp/Vector/VectorOfRect2d.cs
- src/OpenCvSharp/Vector/VectorOfRotatedRect.cs
- src/OpenCvSharp/Vector/VectorOfVec2f.cs
- src/OpenCvSharp/Vector/VectorOfVec3f.cs
- src/OpenCvSharp/Vector/VectorOfVec4f.cs
- src/OpenCvSharp/Vector/VectorOfVec4i.cs
- src/OpenCvSharp/Vector/VectorOfVec6d.cs
- src/OpenCvSharp/Vector/VectorOfVec6f.cs
- src/OpenCvSharp/Vector/VectorOfVectorFloat.cs
- src/OpenCvSharp/Vector/VectorOfVectorInt.cs
- src/OpenCvSharpExtern/core.h
- test/OpenCvSharp.Tests/core/RNGTest.cs
> add SetTheRNG

- nuget/OpenCvSharp4.Windows.nuspec
- nuget/OpenCvSharp4.nuspec
- nuget/OpenCvSharp4.runtime.ubuntu.16.04-x64.csproj
- nuget/OpenCvSharp4.runtime.ubuntu.16.04-x64.nuspec
- nuget/OpenCvSharp4.runtime.ubuntu.18.04-x64.csproj
- nuget/OpenCvSharp4.runtime.ubuntu.18.04-x64.nuspec
- nuget/OpenCvSharp4.runtime.uwp.nuspec
- nuget/OpenCvSharp4.runtime.win.nuspec
- src/OpenCvSharp.Blob/OpenCvSharp.Blob.csproj
- src/OpenCvSharp.Extensions/OpenCvSharp.Extensions.csproj
- src/OpenCvSharp/OpenCvSharp.csproj
- src/OpenCvSharp/PInvoke/NativeMethods/NativeMethods.cs
- src/OpenCvSharp/PInvoke/NativeMethods/NativeMethods_imgcodecs.cs
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
- test/OpenCvSharp.Tests/imgcodecs/ImgCodecsTest.cs
- tool/OpenCvSharp.ReleaseMaker/MainForm.cs
- `imread` can read unicode strings 
- `imwrite` doesn't seem to support unicode strings?
`NETSTANDARD2_1 || NETCOREAPP2_1 || NET48`
https://apisof.net/catalog/System.Runtime.InteropServices.UnmanagedType.LPUTF8Str
> Try supporting Unicode characters in imgcodecs on net48/netstandard2.1/netcoreapp2.1

- .circleci/config.yml
- docker/appengine-aspnetcore2.2-opencv4.2.0/Dockerfile
- docker/appengine-aspnetcore3.1-opencv4.2.0/Dockerfile
- docker/ubuntu18-dotnetcore3.1-opencv4.2.0/Dockerfile
https://hub.docker.com/r/shimat/appengine-aspnetcore3.1-opencv4.2.0
> add Dockerfiles

- src/OpenCvSharp/Modules/aruco/CvAruco.cs
- src/OpenCvSharp/Modules/aruco/DetectorParameters.cs
- src/OpenCvSharp/Modules/aruco/Enum/CornerRefineMethod.cs
- src/OpenCvSharp/Modules/aruco/Enum/PredefinedDictionaryName.cs
- src/OpenCvSharp/PInvoke/NativeMethods/NativeMethods_aruco.cs
- src/OpenCvSharpExtern/aruco.h
- src/OpenCvSharpExtern/include_opencv.h
Added new detector parameters and AprilTag dictionaries.
Fixed crash when creating DetectorParameters.
Let me know if you have any questions.
> Added some aruco functions

- src/OpenCvSharp/Modules/objdetect/QRCodeDetector.cs
- src/OpenCvSharp/PInvoke/NativeMethods/NativeMethods_stdvector.cs
- src/OpenCvSharp/Vector/VectorOfString.cs
- src/OpenCvSharpExtern/objdetect_QRCodeDetector.h
- src/OpenCvSharpExtern/std_vector.h
- test/OpenCvSharp.Tests/objdetect/QRCodeDetectorTest.cs
- test/OpenCvSharp.Tests/videoio/VideoWriterTest.cs
> Fix VectorOfString bug

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- src/OpenCvSharp/Modules/calib3d/Enum/HandEyeCalibrationMethod.cs
- src/OpenCvSharp/PInvoke/NativeMethods/calib3d/NativeMethods_calib3d.cs
- src/OpenCvSharpExtern/calib3d.h
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
> add calibrateHandEye

- src/OpenCvSharp/Modules/videoio/VideoCapture.cs
> Fix VideoCapture.ConvertRGB

- src/OpenCvSharp/Cv2/Cv2_imgproc.cs
- src/OpenCvSharp/PInvoke/NativeMethods/imgproc/NativeMethods_imgproc.cs
- src/OpenCvSharpExtern/imgproc.h
- test/OpenCvSharp.Tests/imgproc/ImgProcTest.cs
> added ApplyColorMap overload

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- src/OpenCvSharpExtern/calib3d.h
> InitCameraMatrix2D: double -> float

- src/OpenCvSharp/Cv2/Cv2_imgproc.cs
- src/OpenCvSharp/PInvoke/NativeMethods/imgproc/NativeMethods_imgproc.cs
> added CornerHarris and CornerMinEigenVal

- nuget/OpenCvSharp4.nuspec
- tool/OpenCvSharp.ReleaseMaker/MainForm.cs
> Include WpfExtensions in package

- src/OpenCvSharp/Modules/core/Mat/Mat.cs
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
- test/OpenCvSharp.Tests/core/MatTest.cs
```c#
using var submat = mat[10..20, 30..40];
using var rows = mat.RowRange(200..);
using var cols = mat.ColRange(..^300);
```
> Mat.Submat supports System.Range

- .github/workflows/macos10.yml
- src/OpenCvSharp/Cv2/Cv2_imgproc.cs
- src/OpenCvSharp/PInvoke/NativeMethods/imgproc/NativeMethods_imgproc.cs
- test/OpenCvSharp.Tests/imgproc/ImgProcTest.cs
> fix CornerHarris

- src/OpenCvSharp/Cv2/Cv2_imgproc.cs
- src/OpenCvSharpExtern/imgproc.h
- test/OpenCvSharp.Tests/imgproc/ImgProcTest.cs
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/contours.cpp#L1793
> findContours: InputOutputArray -> InputArray

- src/OpenCvSharpExtern/core.h
- src/OpenCvSharpExtern/imgproc.h
- test/OpenCvSharp.Tests/imgproc/ImgProcTest.cs
> fix unused arguments

- src/OpenCvSharp/Cv2/Cv2_imgproc.cs
- src/OpenCvSharp/Modules/core/Mat/Mat_CvMethods.cs
- src/OpenCvSharp/Modules/imgproc/Enum/HoughMethods.cs
> Added HoughMethods.GradientAlt

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- src/OpenCvSharp/PInvoke/NativeMethods/calib3d/NativeMethods_calib3d.cs
- src/OpenCvSharpExtern/calib3d.h
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
- test/OpenCvSharp.Tests/calib3d/Calib3dTest.cs
- test/OpenCvSharp.Tests/text/DetectTextSWTTest.cs
> Fix RecoverPose

- docker/al2-dotnet5-opencv4.5.0/Dockerfile
- docker/al2-opencv4.5.0/Dockerfile
> Add Dockerfiles for amazonlinux2

- .github/workflows/windows.yml
- OpenCvSharp.sln.DotSettings
- nuget/OpenCvSharp4.Windows.nuspec
- nuget/OpenCvSharp4.WpfExtensions.nuspec
- tool/OpenCvSharp.NupkgBetaRemover/Program.cs
- tool/OpenCvSharp.ReleaseMaker/MainForm.Designer.cs
- tool/OpenCvSharp.ReleaseMaker/MainForm.cs
> fix WpfExtensions dependency

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- src/OpenCvSharp/Modules/calib3d/Enum/RobotWorldHandEyeCalibrationMethod.cs
- src/OpenCvSharp/PInvoke/NativeMethods/calib3d/NativeMethods_calib3d.cs
- src/OpenCvSharpExtern/calib3d.h
- test/OpenCvSharp.Tests/calib3d/Calib3dTest.cs
> Add CalibrateRobotWorldHandEye

- OpenCvSharp.sln.DotSettings
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/NativeMethods_stdvector.cs
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/stitching/NativeMethods_stitching_Matchers.cs
- src/OpenCvSharp/Internal/Vectors/VectorOfImageFeatures.cs
- src/OpenCvSharp/Internal/Vectors/VectorOfVectorByte.cs
- src/OpenCvSharp/Modules/stitching/AffineBestOf2NearestMatcher.cs
- src/OpenCvSharp/Modules/stitching/BestOf2NearestMatcher.cs
- src/OpenCvSharp/Modules/stitching/CvDetail.cs
- src/OpenCvSharp/Modules/stitching/FeaturesMatcher.cs
- src/OpenCvSharp/Modules/stitching/MatchesInfo.cs
- src/OpenCvSharp/Modules/stitching/Stitcher.cs
- src/OpenCvSharpExtern/my_types.h
- src/OpenCvSharpExtern/std_vector.h
- src/OpenCvSharpExtern/std_vector_nesting.h
- src/OpenCvSharpExtern/std_vector_primitive.h
- src/OpenCvSharpExtern/stitching_detail_Matchers.h
- test/OpenCvSharp.Tests/PlatformSpecificFactAttribute.cs
- test/OpenCvSharp.Tests/stitching/CvDetailTest.cs
- test/OpenCvSharp.Tests/stitching/StitchingTest.cs
> Add FeaturesMatcher

- src/OpenCvSharp/Internal/PInvoke/NativeMethods/NativeMethods_xphoto.cs
- src/OpenCvSharp/Modules/xphoto/CvXPhoto.cs
- src/OpenCvSharp/Modules/xphoto/Enum/InpaintTypes.cs
- src/OpenCvSharpExtern/stitching_detail_Matchers.h
- src/OpenCvSharpExtern/xphoto.h
- test/OpenCvSharp.Tests/core/MatTest.cs
> Add new inpainting flags

- src/OpenCvSharp/Internal/PInvoke/NativeMethods/NativeMethods_highgui.cs
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/core/NativeMethods_core_InputArray.cs
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/core/NativeMethods_core_Mat.cs
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/core/NativeMethods_core_OutputArray.cs
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/core/NativeMethods_core_UMat.cs
- src/OpenCvSharp/Modules/core/Enum/AccessFlag.cs
- src/OpenCvSharp/Modules/core/Enum/UMatUsageFlags.cs
- src/OpenCvSharp/Modules/core/InputArray.cs
- src/OpenCvSharp/Modules/core/InputOutputArray.cs
- src/OpenCvSharp/Modules/core/Mat/Mat.cs
- src/OpenCvSharp/Modules/core/Mat/UMat.cs
- src/OpenCvSharp/Modules/core/OutputArray.cs
- src/OpenCvSharp/Modules/highgui/Window.cs
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj.filters
- src/OpenCvSharpExtern/core.cpp
- src/OpenCvSharpExtern/core_InputArray.h
- src/OpenCvSharpExtern/core_Mat.h
- src/OpenCvSharpExtern/core_OutputArray.h
- src/OpenCvSharpExtern/core_UMat.h
- src/OpenCvSharpExtern/highgui.h
- src/OpenCvSharpExtern/my_functions.h
Initial UMat support draft. 
@shimat I tried following your code patterns as closely as I could.
I have tested this doing CalcOpticalFlowFarneback at 1280x720 using mostly UMat, performance on a GTX 1080 Max-Q was  around 20FPS on the GPU vs 4FPS on the Mat/CPU side of things. 
Other functions such as Blur also worked as expected using UMat.
I have not tested all function calls yet.
> UMat support first draft - addsTo #1146, #238 and #965

- src/OpenCvSharp/Cv2/Cv2_highgui.cs
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/NativeMethods_highgui.cs
- src/OpenCvSharp/Modules/highgui/Enum/WindowFlags.cs
- src/OpenCvSharp/Modules/highgui/Enum/WindowPropertyFlags.cs
- src/OpenCvSharp/Modules/highgui/Window.cs
- src/OpenCvSharpExtern/highgui.h
- src/OpenCvSharpExtern/include_opencv.h
- test/OpenCvSharp.Tests/highgui/HighGuiTest.cs
> organize window constructors, rename enums, add handle getter

- OpenCvSharp.sln.DotSettings
- src/OpenCvSharpExtern/core_UMat.h
- test/OpenCvSharp.Tests/core/UMatTest.cs
> Add UMat tests

- .github/workflows/publish_nuget.yml
- tool/OpenCvSharp.NupkgBetaRemover/Program.cs
> GHA workflow to publish NuGet packages

- src/OpenCvSharpExtern/tracking.h
- src/OpenCvSharpExtern/video_tracking.h
> TrackerGOTURN: tracking -> video

- src/OpenCvSharp/Internal/PInvoke/NativeMethods/ximgproc/NativeMethods_ximgproc_RidgeDetectionFilter.cs
- src/OpenCvSharp/Modules/core/Struct/MatType.cs
- src/OpenCvSharp/Modules/ximgproc/RidgeDetectionFilter.cs
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj.filters
- src/OpenCvSharpExtern/ximgproc.cpp
- src/OpenCvSharpExtern/ximgproc_RidgeDetectionFilter.h
- test/OpenCvSharp.Tests/imgproc/ImgProcTest.cs
- test/OpenCvSharp.Tests/ximgproc/RidgeDetectionFilterTest.cs
> RidgeDetectionFilter

- src/OpenCvSharp/Internal/PInvoke/NativeMethods/photo/NativeMethods_photo_HDR.cs
- src/OpenCvSharp/Modules/photo/CalibrateRobertson.cs
- src/OpenCvSharpExtern/photo_HDR.h
> Add CalibrateRobertson

- src/OpenCvSharp/Fundamentals/ResourcesTracker.cs
Though we can create and track UMat using generics, I think adding these two helper functions can be more friendly to users who want to use ResourcesTracker to track UMat (as I didn't realized this until I checked the source code 🤣)
Again, thanks for your great effort of making this project!
> feat: add direct support of UMat in tracker

- src/OpenCvSharp/Modules/core/Enum/GemmFlags.cs
- src/OpenCvSharp/Modules/imgproc/Enum/MorphTypes.cs
> Fix incorrect [Flags] attributes

- src/OpenCvSharp/Modules/video/BackgroundSubtractorKNN.cs
- test/OpenCvSharp.Tests/video/BackgroundSubtractorKNNTest.cs
This will fix: https://github.com/shimat/opencvsharp/issues/1425
> Fix access violation BackgroundSubtractorKNN

- nuget/OpenCvSharp4.Extensions.nuspec
- nuget/OpenCvSharp4.Windows.nuspec
- nuget/OpenCvSharp4.WpfExtensions.nuspec
- nuget/OpenCvSharp4.nuspec
- nuget/OpenCvSharp4.runtime.uwp.nuspec
- nuget/OpenCvSharp4.runtime.win.nuspec
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/imgproc/NativeMethods_imgproc_LineSegmentDetector.cs
- src/OpenCvSharp/Modules/imgproc/Enum/LineSegmentDetectorModes.cs
- src/OpenCvSharp/Modules/imgproc/LineSegmentDetector.cs
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj.filters
- src/OpenCvSharpExtern/imgproc.cpp
- src/OpenCvSharpExtern/imgproc_LineSegmentDetector.h
Due to restored LSD in OpenCV 4.5.4, i've implemented it back to opencvsharp
> Restore LineSegmentDetector

- src/OpenCvSharp/Fundamentals/MatMemoryManager.cs
- src/OpenCvSharp/Modules/core/Mat/Mat.cs
> Add MatMemoryManager and Mat.AsSpan

- .github/workflows/windows.yml
- nuget/OpenCvSharp4.runtime.win.nuspec
> Fix nuget pack error of runtime.win

- .github/workflows/docker-ubuntu20.yml
- .github/workflows/wasm.yml
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/core/NativeMethods_core.cs
- src/OpenCvSharp/Modules/core/Struct/RotatedRect.cs
- src/OpenCvSharp/OpenCvSharp.csproj
- src/OpenCvSharpExtern/core.h
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
- test/OpenCvSharp.Tests/core/RotatedRectTest.cs
> fix RotatedRect error

- src/OpenCvSharp/Modules/ml/RTrees.cs
> RTrees.ActiveVarCount: bool -> int
