- src/OpenCvSharp/Src/Core/Cv_C.cs
- src/OpenCvSharp/Src/PInvoke/NativeMethods.cs
Hi first time to contribute here. It is a relatively minor change to access the return value (reprojection error) from CalibrateCamera2 when using the 'C' style interfaces.
Separate function added with ‘out reprojectionError’ value so as to have less risk of breaking compatibility with any existing code, versus alternate of changing the return value on all existing function variants.
> Support using the reprojection error return value from CalibrateCamera2.

- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
This means that if the nonfree and stitching dlls are missing, then OpenCvSharpExtern can still be loaded.
The missing dlls will be reported by WindowsLibraryLoader.LoadLibrary, but you can still use OpenCvSharp for the free functionality.
(I've also updated the Debug target to use the 2410 libs/dlls like the Release target)
> Delay-link the nonfree and stitching libraries.

- src/OpenCvSharp.CPlusPlus/Cv2/Cv2_calib3d.cs
Hi, I think I found a couple of minor interop bugs, where using the wrong native methods call causes an AccessViolationException.
Are these changes useful as they are?
> Potential bugs in calib3d interop

- sample/CStyleSamplesCS/Samples/BinarizationMethods.cs
- src/OpenCvSharp.Extensions/Binarizer.cs
Niblack のノイズ耐性版である二値化の Nick を追加しました。
エッジをクリアに出すことができ、パラメーターは少なく扱いやすい特徴があります。
参考
「Comparison of Niblack inspired Binarization methods for ancient documents」
http://www.math-info.univ-paris5.fr/~vincent/articles/DRR_nick_binarization_09.pdf
> Nick binalization

- src/OpenCvSharpExtern/CMakeLists.txt
This pull request is based on the conversation of https://github.com/shimat/opencvsharp/issues/85 .
Current libOpenCvSharpExtern does not support UNIX.
I created a pull request to support UNIX again.
Please see the above conversation for the detail.
> Support UNIX

- src/OpenCvSharpExtern/CMakeLists.txt
Please support `sudo make install` for UNIX.
> Install libOpenCvSharpExtern.so for UNIX

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
- src/OpenCvSharpExtern/calib3d.h
OpenCvSharp.NativeMethods.calib3d_calibrateCamera_vector
Received exception:
OpenCvSharp.OpenCVException: objectPoints should contain vector of vectors of points of type Point3f
Original code was cpp and c# code was using Point2d and Point3d, when opencv requires Point2f and Point3f.
Thanks for all the work you have done on this!
> calib3d_calibrateCamera_vector

- src/OpenCvSharp/modules/core/Mat/MatOfT.cs
From mailing list,  Request sample Camera calibration for Version 3.0 please. #132
MatOfT bounds check should only throw error if 'array is less than' , rather than 'less than or equal to'.
Tested with sample code provided in post.
Requires fix from my previous commit also.
> Request sample Camera calibration for Version 3.0 please. #132

- src/OpenCvSharp/Cv2/Cv2_core.cs
いつも大変便利に使わせていただいております．
関数名がおかしかったので，報告しました．（単なるタイプミスだと思いますが）
修正箇所はタイトルの通りです．
> FetNumberOfCpus() -> GetNumberOfCpus()

- src/OpenCvSharp/Cv2/Cv2_calib3d.cs
Re-applying a fix I made a while ago. It looks like this issue has returned with the switch to OpenCV 3
> StereoCalibrate - Correct point type is Point3f not Point3d

- src/OpenCvSharpExtern/calib3d.h
StereoCalibrate - cv::stereoCalibrate requires Point2f and Point3f instead of Point2d and Point3d. See #227
> StereoCalibrate - requires Point2f and Point3f

- src/OpenCvSharp/modules/core/Mat/Mat.cs
Read till the end of stream when read Mat using Mat.FromStream
Fix a problem that Mat.FromStream may read only avaliable bytes in the stream and return broken image
> Fix a problem that Mat.FromStream may read only avaliable bytes in the stream and return broken image

- src/OpenCvSharp/PInvoke/core/NativeMethods_core_Mat.cs
- src/OpenCvSharp/modules/core/Mat/Mat.cs
- src/OpenCvSharpExtern/core_Mat.h
Add core_Mat_diag3 to call cv::Mat::diag(Mat&) and fix OpenCVSharp.Mat.Diag(Mat) bug
> #329: Mat.Diag(Mat) does not reutrn a square diagonal matrix

- src/OpenCvSharp/Cv2/Cv2_imgproc.cs
Cv2.RotatedRectangle(r1, r2, Point2f[] calls wrong NativeMethod function, resulting in an exception. (reported as issue #411)
> Cv2.RotatedRectangle(r1, r2, Point2f[] intersection) throws exception

- src/OpenCvSharp/Modules/superres/DenseOpticalFlowExt.cs
fix CreateDualTVL1 & CreateDualTVL1_CUDA - they were creating instances of Farneback Optical Flow algorithms.
> fix CreateDualTVL1 & CreateDualTVL1_CUDA

- src/OpenCvSharp/Modules/shape/ShapeContextDistanceExtractor.cs
ShapeContextDistanceExtractor Ptr<>.Get called wrong NativeMethod.
> fix ShapeContextDistanceExtractor Ptr<>.Get

- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
use consistent libs for release and debug builds. Debug config would not build.
> update libs used to build OpenCvSharpExtern.dll

- src/OpenCvSharp/Vector/VectorOfCvString.cs
- src/OpenCvSharp/Vector/VectorOfPoint3f.cs
fix constructors - VectorOfCvString() and VectorOfPoint3f() - both called incorrect NativeMethod... functions, possibly resulting in corrupt memory.
> fix constructors for VectorOfCvString and VectorOfPoint3f

- src/OpenCvSharp/Modules/dnn/Net.cs
- src/OpenCvSharp/PInvoke/dnn/NativeMethods_dnn_Net.cs
- src/OpenCvSharpExtern/dnn_Net.h
> add dnn::Net functions

- src/OpenCvSharp/Modules/core/Mat/MatOfT.cs
See https://github.com/shimat/opencvsharp/issues/471
> Fixed heap corruption due to using Mat and MatOfT.

- nuget/OpenCvSharp3-AnyCPU.nuspec
- nuget/OpenCvSharp3-WithoutDll.nuspec
- src/OpenCvSharp.Blob/CvContourPolygon.cs
- src/OpenCvSharp.Blob/OpenCvSharp.Blob.csproj
- src/OpenCvSharp.Extensions/BitmapSourceConverter.cs
- src/OpenCvSharp.Extensions/OpenCvSharp.Extensions.csproj
- src/OpenCvSharp.Extensions/WriteableBitmapConverter.cs
- src/OpenCvSharp.ReleaseMaker/MainForm.cs
- src/OpenCvSharp/Modules/core/FileStorage.cs
- src/OpenCvSharp/Modules/core/InputArray.cs
- src/OpenCvSharp/Modules/core/Mat/Mat.cs
- src/OpenCvSharp/Modules/face/Facemark/FacemarkAAM.cs
- src/OpenCvSharp/Modules/face/Facemark/FacemarkLBF.cs
- src/OpenCvSharp/Modules/objdetect/CascadeClassifier.cs
- src/OpenCvSharp/Modules/superres/FrameSource.cs
- src/OpenCvSharp/OpenCvSharp.csproj
- src/OpenCvSharp/PInvoke/NativeMethods.cs
- src/OpenCvSharp/PInvoke/WindowsLibraryLoader.cs
- src/OpenCvSharp/Util/DynamicInvoker.cs
- src/OpenCvSharp/Util/MarshalHelper.cs
- src/OpenCvSharp/Util/MemoryHelper.cs
- src/OpenCvSharp/Util/StringArrayAddress.cs
- src/OpenCvSharp/Util/TypeHelper.cs
- src/OpenCvSharpExtern/std_vector.h
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
- test/OpenCvSharp.Tests/extensions/BitmapConverterTest.cs
- Remove `netstandard1.6` and `netcoreapp1.0` support
- OpenCvSharp.Extensions is available on netstandard2.0
- Close #392
> Support netstandard2.0

- src/OpenCvSharp/Modules/core/Struct/Rect2d.cs
- src/OpenCvSharp/Modules/tracking/MultiTracker.cs
- src/OpenCvSharp/Modules/tracking/Tracker.cs
- src/OpenCvSharp/Modules/tracking/TrackerBoosting.cs
- src/OpenCvSharp/Modules/tracking/TrackerGOTURN.cs
- src/OpenCvSharp/Modules/tracking/TrackerKCF.cs
- src/OpenCvSharp/Modules/tracking/TrackerMIL.cs
- src/OpenCvSharp/Modules/tracking/TrackerMOSSE.cs
- src/OpenCvSharp/Modules/tracking/TrackerMedianFlow.cs
- src/OpenCvSharp/Modules/tracking/TrackerTLD.cs
- src/OpenCvSharp/PInvoke/NativeMethods_stdvector.cs
- src/OpenCvSharp/PInvoke/NativeMethods_tracking.cs
- src/OpenCvSharp/PInvoke/traking/NativeMethods_tracking.cs
- src/OpenCvSharp/PInvoke/traking/NativeMethods_tracking_MultiTracker.cs
- src/OpenCvSharp/Vector/VectorOfRect2d.cs
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj.filters
- src/OpenCvSharpExtern/std_vector.h
- src/OpenCvSharpExtern/tracking.cpp
- src/OpenCvSharpExtern/tracking.h
- src/OpenCvSharpExtern/tracking_MultiTracker.h
- test/OpenCvSharp.Tests/tracking/MultiTrackerTest.cs
- test/OpenCvSharp.Tests/tracking/TrackerMOSSETest.cs
> Add TrackerMOSSE and MultiTracker

- src/OpenCvSharp/Modules/stitching/Stitcher.cs
- src/OpenCvSharp/PInvoke/NativeMethods_stitching.cs
- src/OpenCvSharpExtern/stitching.h
- test/OpenCvSharp.Tests/stitching/StitchingTest.cs
Wrappers for cv::createStitcherScans is missing from the implementation, in our use case, using createStitcherScans pipeline saved 50% of processing time and also produced the correct result, so I would like to submit a PR to add the wrappers of stitching pipeline for scan images.
> Added wrappers for cv::createStitcherScans method

- src/OpenCvSharp/Modules/core/Struct/Size2d.cs
The `OpenCvSharp.Size2d` constructor that takes two `double` arguments casts the arguments to `int` before setting its fields. This pull request aims to fix this.
> Fix loss of precision in OpenCvSharp.Size2d constructor

- src/OpenCvSharp/Modules/core/Mat/Mat.cs
- src/OpenCvSharp/Modules/core/Mat/MatOfT.cs
- src/OpenCvSharp/PInvoke/core/NativeMethods_core_Mat.cs
- src/OpenCvSharpExtern/core_Mat.h
When any successor of MatOfT (e.g. MatOfFloat) is created not using another Mat (e.g. using new MatOfFloat(128, 128)) then it is not deleted properly on C++ side, causing memory leaks in unmanaged memory. 
The reason is that DisposeUnmanaged does nothing in MatOfT, but the constructor allocates the memory!
Fixed in a way that DisposeUnmanaged and DisposeManaged is not overriden and called properly as for other Mats. SourceMat is removed. To handle the problem when MatOfT is created from another Mat, the cv::Mat(const Mat & m) constructor is called on C++ side, which will result in increment of a refcount on related C++ Mat so when desctructor is called multiple times it is not a problem, because the first call will just decrement the refcount.
Tested with VisualStudio 2017 memory profiler …
> Fix memory issue in MatOfT

- src/OpenCvSharp.Blob/BlobRenderer.cs
> BlobRenderer: draw MaxX and MaxY pixels

- src/OpenCvSharp/Modules/imgproc/Enum/ColormapTypes.cs
OpenCV supports 20 types of colormap from 4.1.0 but we can't use it because an enum type in this library is not up-to-date.
Edit: I could use other color maps if I cast value explicitly. This PR is for convenience.
> OpenCv 4.1.0 ColormapTypes

- src/OpenCvSharp/Modules/dnn/Net.cs
Recently OpenCV merged a pull request [https://github.com/opencv/opencv/pull/14827](https://github.com/opencv/opencv/pull/14827) which extends the DNN portion of OpenCV to include CUDA acceleration.  I have tested and confirmed this works on the Nvidia Nano ARM64 and this repo. This enum is just to match what is currently the active enum in OpenCV [Current enums](https://github.com/opencv/opencv/blob/613c12e59015f4bd7909916ceee195edd7ef88d0/modules/dnn/include/opencv2/dnn/dnn.hpp#L65)
> Updated DNN Target / Backend enum to include new support for CUDA

- src/OpenCvSharp/Cv2/Cv2_video.cs
> fix CalcOpticalFlowPyrLK

- src/OpenCvSharp/Modules/videoio/VideoCapture.cs
- src/OpenCvSharp/PInvoke/NativeMethods/NativeMethods_videoio.cs
- src/OpenCvSharpExtern/videoio.h
- test/OpenCvSharp.Tests/videoio/VideoCaptureTest.cs
Fix #854 
Add `Retrieve(Mat)` and `Read(Mat)` overload methods to prevent memory leaks
> add VideoCapture overloads

- src/OpenCvSharp/Modules/face/Facemark/Facemark.cs
- src/OpenCvSharpExtern/face_Facemark.h
Fixes #653
As suggested by @0x0aNL [here](https://github.com/VahidN/OpenCVSharp-Samples/issues/10#issuecomment-520380701), I fixed Facemark.Fit and corresponding function in OpenCvSharpExtern/face_Facemark.h.  
```cs
OpenCvSharp.Face.Facemark faceMark = OpenCvSharp.Face.FacemarkLBF.Create();
faceMark.LoadModel("lbfmodel.yaml");
// faceRects is an array of Rect - bonding boxes of faces detected in image
InputArray facesArray = InputArray.Create(facesRects); 
Point2f[][] landmarks;
faceMark.Fit(image, facesArray, out landmarks);
```
> Fix #653 - Face.Facemark.Fit output

- .github/workflows/macos10.yml
- nuget/OpenCvSharp4.runtime.macos.10.15-x64.csproj
- nuget/OpenCvSharp4.runtime.macos.10.15-x64.nuspec
- src/OpenCvSharpExtern/CMakeLists.txt
- test/OpenCvSharp.Tests/core/UtilityTest.cs
1. GitHub action **build workflow for macOS**. 
2. **macOS native NuGet package** and NuGet .csproj. 
3. Minor change in OpenCvSharpExtern/CMakeLists.txt so the build script finds libraries installed via Homebrew. 
4. Skip GetAndSetNumThreads on macOS because [GCD framework on Apple platforms causes a different behavior of SetNumThreads](https://docs.opencv.org/3.4/db/de0/group__core__utils.html#gae78625c3c2aa9e0b83ed31b73c6549c0) - and [GCD](https://developer.apple.com/documentation/DISPATCH) is the recommended multicore framework on Apple platforms.
> macOS build: workflow, build fixes, native NuGet package and test changes

- src/OpenCvSharp/Modules/core/Struct/Rect.cs
- test/OpenCvSharp.Tests/core/RectTest.cs
This makes Rect.FromLTRB behave like System.Drawing.Rectangle.Rect.FromLTRB
Fix #1051
> fix #1051 - Rect.FromLTRB should not add +1 to Width and Height

- src/OpenCvSharp/Modules/ml/ANN_MLP.cs
- test/OpenCvSharp.Tests/ml/ANN_MLPTest.cs
> ANN_MLP: add SetActivationFunction and SetTrainMethod

- src/OpenCvSharp/Modules/video/Tracker.cs
- src/OpenCvSharp/Modules/video/TrackerGOTURN.cs
- src/OpenCvSharp/Modules/video/TrackerMIL.cs
- src/OpenCvSharp/PInvoke/NativeMethods/traking/NativeMethods_tracking.cs
- src/OpenCvSharp/PInvoke/NativeMethods/video/NativeMethods_video_tracking.cs
- src/OpenCvSharpExtern/tracking.h
- src/OpenCvSharpExtern/video_tracking.h
- https://github.com/opencv/opencv/blob/master/modules/video/include/opencv2/video/tracking.hpp
- https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/include/opencv2/tracking.hpp
In OpenCV4.5.1, Tracker, TrackerMIL and TrackerGOTURN move from contrib tracking to video.
Fix #1136
> Move Tracker implementation from tracking to video

- src/OpenCvSharp/Modules/highgui/Window.cs
- test/OpenCvSharp.Tests/highgui/HighGuiTest.cs
> call cv::destroyWindow in Window.Dispose()

- src/OpenCvSharp/Cv2/Cv2_highgui.cs
Fixed the type of parameter 'flags' in function 'GetMouseWheelDelta' to be same as the type of parameter 'flags' in delegate 'MouseCallback'.
> Fix parameter type in GetMouseWheelDelta

- nuget/OpenCvSharp4.nuspec
- src/OpenCvSharp.Extensions/OpenCvSharp.Extensions.csproj
- src/OpenCvSharp.WpfExtensions/OpenCvSharp.WpfExtensions.csproj
- src/OpenCvSharp/Modules/imgcodecs/Enum/ImwriteFlags.cs
- test/OpenCvSharp.Tests/OpenCvSharp.Tests.csproj
> Add new ImwriteFlags values

- src/OpenCvSharp/Internal/PInvoke/NativeMethods/NativeMethods_videoio.cs
- src/OpenCvSharp/Modules/videoio/Enum/VideoAccelerationType.cs
- src/OpenCvSharp/Modules/videoio/Enum/VideoCapturePara.cs
- src/OpenCvSharp/Modules/videoio/Enum/VideoCaptureProperties.cs
- src/OpenCvSharp/Modules/videoio/Enum/VideoWriterPara.cs
- src/OpenCvSharp/Modules/videoio/Enum/VideoWriterProperties.cs
- src/OpenCvSharp/Modules/videoio/VideoCapture.cs
- src/OpenCvSharp/Modules/videoio/VideoWriter.cs
- src/OpenCvSharpExtern/videoio.h
- add missing native methods for hardware acceleration
- add methods of video Capture/Writer for hardware acceleration
- add some missing properties of video Capture/Writer
- add video Capture/Writer parameter for hardware acceleration
Current HW acceleration types support matrix, for more details please check the [link](https://github.com/opencv/opencv/wiki/Video-IO-hardware-acceleration#video-io-hardware-acceleration) 
please review!
> enable hardware acceleration of VideoCapture and VideoWriter

- src/OpenCvSharp/Modules/core/Mat/Mat.cs
- src/OpenCvSharp/Modules/core/Mat/MatOfT.cs
- test/OpenCvSharp.Tests/core/MatTest.cs
This problem can be seen as a specification of OpenCV.
Close #1288
> Fixed behavior of Mat.clone for empty Mat

- src/OpenCvSharp/Cv2/Cv2_imgcodecs.cs
- src/OpenCvSharp/Internal/PInvoke/NativeMethods/imgproc/NativeMethods_imgproc_Segmentation.cs
- src/OpenCvSharp/Modules/core/Mat/UMat.cs
- src/OpenCvSharp/Modules/highgui/Window.cs
- src/OpenCvSharp/Modules/imgproc/IntelligentScissorsMB.cs
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj
- src/OpenCvSharpExtern/OpenCvSharpExtern.vcxproj.filters
- src/OpenCvSharpExtern/imgproc.cpp
- src/OpenCvSharpExtern/imgproc_Segmentation.h
- test/OpenCvSharp.Tests/imgproc/IntelligentScissorsMBTest.cs
> add IntelligentScissorsMB
